name: emotion_detector
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  animated_emoji: ^3.0.0
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_svg: ^2.0.9
  http_parser: ^4.0.2
  image_picker: ^1.0.5
  modal_progress_hud_nsn: ^0.4.0
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
